import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import React from 'react';
import { satoshi } from '@/font'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{overflowX: 'hidden',}}>
      <body className={satoshi.className} style={{ margin: '0'}}>
          {children}
        </body>
    </html>
  )
}

